#pragma once
#include <Poco/Net/NetSSL.h>
#include <Poco/Crypto/Crypto.h>
#include <iostream>
#include <fstream>
#include <Poco/JSON/Parser.h>
//#include <Poco/JSON/Array.h>
#include <Poco/Dynamic/Var.h>
#include <Poco/File.h>
#include <Poco/Path.h>
#include <Poco/SimpleFileChannel.h>
#include <Poco/FormattingChannel.h>
#include <Poco/Logger.h>
#include <Poco/PatternFormatter.h>
#include <Poco/Net/HTTPClientSession.h>
#include <Poco/Net/HTTPRequest.h>
#include <Poco/Net/HTTPResponse.h>
#include <Poco/URI.h>
#include <Poco/StreamCopier.h>
#include <Poco/Net/OAuth20Credentials.h>
#include <Poco/Net/HTTPSClientSession.h>
#include <Poco/Net/Context.h>